### ISSUE TITLE
PHP Notice:  Undefined index: weaponkills

### ISSUE THREAD

**Issue by marshyonline** [tyger07/BF4-Server-Stats#19]
I can not seem to get signatures to work. Server banners are ok, Player profiles are fine just no sig.
Stock fresh install running XAMP on windows.

[18-Apr-2016 18:17:59 Australia/Sydney] PHP Notice:  Undefined index: weaponkills in E:\wwwdata\stats\common\signature\signature.php on line 126

**Comment by tyger07** [comment]
Ah, yes, there is a mistake.  I will fix it up as soon as I have a chance.

**Comment by marshyonline** [comment]
Sweet Thank you!

**Comment by tyger07** [comment]
It's an easy fix. It's just an old piece of code referencing a variable I don't use any more.  I just forgot to remove it.
I am busy at the moment.  I will try to fix it in about 8 hours.

**Comment by tyger07** [comment]
It should now be fixed.
