### ISSUE TITLE
Live Scoreboard is broken on new Ubuntu 16.04 install

### ISSUE THREAD

**Issue by FroToe** [tyger07/BF4-Server-Stats#25]
I just decided to install fresh everything on a new host running Ubuntu 16.04 and move my DB over and install this software while I'm about it (been running the stats logger, but not with the spiffy web interface).  Live Scoreboard doesn't work.  Seems mysql has changed a little and now rejects one of the SELECT requests in live-scoreboard.php .

### Steps Performed to Reproduce this Behavior:
MYSQLD version                  5.7.22-0ubuntu0.16.04.1 

From a mysql command line connected to and using your DB...

This works: SELECT cp.`Soldiername`, cp.`Score`, cp.`Kills`, cp.`Deaths`, cp.`TeamID`, cp.`SquadID`, cp.`CountryCode`, sub.`PlayerID` FROM `tbl_currentplayers` cp LEFT JOIN ( SELECT tpd.`PlayerID`, tpd.`SoldierName` FROM `tbl_playerdata` tpd INNER JOIN `tbl_server_player` tsp ON tsp.`PlayerID` = tpd.`PlayerID` INNER JOIN `tbl_playerstats` tps ON tps.`StatsID` = tsp.`StatsID` WHERE tpd.`GameID` = 1 AND tsp.`ServerID` = 10) sub ON sub.`SoldierName` = cp.`SoldierName` WHERE cp.`ServerID` = 10 AND cp.`TeamID` = 1 GROUP BY cp.`SoldierName`, sub.PlayerID ORDER BY Score DESC;

This fails: SELECT cp.`Soldiername`, cp.`Score`, cp.`Kills`, cp.`Deaths`, cp.`TeamID`, cp.`SquadID`, cp.`CountryCode`, sub.`PlayerID` FROM `tbl_currentplayers` cp LEFT JOIN ( SELECT tpd.`PlayerID`, tpd.`SoldierName` FROM `tbl_playerdata` tpd INNER JOIN `tbl_server_player` tsp ON tsp.`PlayerID` = tpd.`PlayerID` INNER JOIN `tbl_playerstats` tps ON tps.`StatsID` = tsp.`StatsID` WHERE tpd.`GameID` = 1 AND tsp.`ServerID` = 10) sub ON sub.`SoldierName` = cp.`SoldierName` WHERE cp.`ServerID` = 10 AND cp.`TeamID` = 1 GROUP BY cp.`SoldierName` ORDER BY Score DESC;

The error is:

ERROR 1055 (42000): Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sub.PlayerID' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

It's upset that sub.PlayerID is not in the GROUP BY.  I'm not positive my solution of just sticking it in there will fix it correctly, but it seems to.

I changed common/home/scoreboard-live.php to modify the select which begins: "SELECT cp.`Soldiername`, cp.`Score`, cp.`Kills`, cp.`Deaths`, cp.`TeamID`, cp.`SquadID`, cp.`CountryCode`, sub.`PlayerID`..." to put ", sub.'PlayerID'" on the GROUP BY clause and it works.

**Comment by tyger07** [comment]
Thank you!  I will do some testing.

**Comment by tyger07** [comment]
I don't  really know the technical difference, but your solution appears to be agreeable and provide the intended result.
