### ISSUE TITLE
Request: Listing Stats per Weapon

### ISSUE THREAD

**Issue by mambochambo** [tyger07/BF4-Server-Stats#27]
### Expected Behavior:
Hello, is it possible to implement a Function to request the listing of Weaponstats, a Leadingboard for each listed Weapon?

### Actual Behavior:
No option to get a List for special Weapon

### Steps Performed to Reproduce this Behavior:
No Option given.

**Comment by tyger07** [comment]
There are just so many different weapons available.  It becomes absurd and meaningless.  Just listing every possible weapon is almost absurd on its own.

Making the data meaningful and interesting is something that I find challenging.
