### ISSUE TITLE
Es werden Keine Spieler Daten im BF4-Server-Stats angezeigt 

### ISSUE THREAD

**Issue by dieter2308** [tyger07/BF4-Server-Stats#29]
### Expected Behavior:
Hallo , Ich habe das Procon installiert , Spieler werden in der Datenbank gespeichert , aber sie werden nicht auf der HP angezeigt . Habe allei einstellungen gemacht .  

Hier der Link http://dfc-funclan.de/bf4stats/index.php

Was könnte das sein ? oder können sie mir da weiter helfen 

Hello, I installed the Procon, players are stored in the database, but they are not displayed on the HP. Alone I made attitudes.
Here is the link http://dfc-funclan.de/bf4stats/index.php
What could that be ? or can you help me further

**Comment by tyger07** [comment]
Sorry, I do not understand. I only understand English.

**Comment by dieter2308** [comment]
hi, I have installed Procon and the plugin PRoCon Chat, GUID, Stats and Map Logger - 1.0.0.3 and your BF4-Server-Stats, but no player data are displayed in BF4-Server-Stats.
Here is the link: http://dfc-funclan.de/bf4stats/index.php

Player data is stored in the database but not shown on the http://dfc-funclan.de/bf4stats/index.php what could that be.
greeting

**Comment by tyger07** [comment]
Sorry, it is quite impossible for me to guess or know.
If you do XpKiller's stats plugin's commands in the game, is XpKiller's plugin able to correctly provide data?

I think the only way I could figure out the answer is if I had access to your database.

**Comment by dieter2308** [comment]
Here the data for the database
Your database login details are:

Username: ds89trial
Database: ds89trial
Password: uAJrEo6gVIdx1qMP

https://pma.ezrcon.com
Server Choice: eu.db.ezrcon.com

If you still need something, write to me. And thanks for the help

**Comment by tyger07** [comment]
It looks like you are using a table suffix of "None" in XpKiller's plugin.  I think that is the problem.  Do not use a table suffix, and then it should work.  In XpKiller's plugin, set the table suffix to blank, not "None".

It would probably be best to delete all of the data and start over.  Otherwise, you could probably stop XpKiller's plugin, change the table suffix in XpKiller's plugin to blank, and then rename all of the tables in the database to remove the suffix "None" at the end of all of the table names.

**Comment by dieter2308** [comment]
Hello again, I tried but it doesn't work, he saves the data in the database but nothing comes up on http://dfc-funclan.de/bf4stats/index.php

I can give you the data for Procon that you can see whether the settings are correct.

I will send the data to you by e-mail if you give me your e-mail address.

**Comment by dieter2308** [comment]
![Screenshot 2021-01-02-teil1](https://user-images.githubusercontent.com/66239731/103455881-32520f00-4cf1-11eb-8028-4c12f2f14577.png)
![Screenshot 2021-01-02-teil2](https://user-images.githubusercontent.com/66239731/103455883-367e2c80-4cf1-11eb-81ea-90df6a63e315.png)

**Comment by dieter2308** [comment]
![Screenshot-datenbank](https://user-images.githubusercontent.com/66239731/103457435-a7c4dc00-4cff-11eb-9c13-85372c596518.png)
![Screenshot-Procondaten](https://user-images.githubusercontent.com/66239731/103457441-ad222680-4cff-11eb-8eca-90aaac21abb7.png)

**Comment by dieter2308** [comment]
picture 1 database
picture 2 Procon

When you're done I'll change the passwords

Thanks for your help

**Comment by tyger07** [comment]
For some reason your tbl_server table was empty.  I don't know why.  I filled in the data, and now it seems to be working.

**Comment by dieter2308** [comment]
great thank you ,
