### ISSUE TITLE
Broken breadcrum link 

### ISSUE THREAD

**Issue by nickm324** [tyger07/BF4-Server-Stats#30]
broken index text above the breadcrumb image. only the tiny word "index" is clickable.

![image](https://user-images.githubusercontent.com/6774571/111403198-994d5600-869a-11eb-8fb9-235d2f398717.png)

**Comment by tyger07** [comment]
I don't think it is broken.  Maybe just not well designed.

What do you think would make it better?  Can you sketch up your proposal?

**Comment by nickm324** [comment]
Not sure I understand the question, why would there be the words above the breadcrumb image that should actually be the hyperlink for the image.

Are you saying whats in the red box in the image below is supposed to be like that?

![image](https://user-images.githubusercontent.com/6774571/111509214-81b5b200-871a-11eb-9398-7028b4cc50e9.png)

**Comment by tyger07** [comment]
Yes, that was the best I could come up with.  It is supposed to be like that.

Index takes you to the server list page (if you have multiple servers).  Since you don't have multiple servers, it just takes you to the home page.

The other option is to make the "***WAAAAAAAABULANCE TDM HARDCORE***" part take you to the home page, and index take you to the server list index page, but since you don't have multiple servers, both links would take you to the home page.  Wouldn't that be redundant?

In your opinion, for it not to be "broken", where do you think "index" should take you?  And what do you think clicking on "***WAAAAAAAABULANCE TDM HARDCORE***" should do?

I am open to changing it, I just don't know how it should be changed.

**Comment by nickm324** [comment]
Well from a software developer point of view, if it was a true breadcrumb The HOME PAGE image would be the the clickable content. so you would have for example the HOME / PLAYER STATS / WHATEVER and the you could click PLAYER STATS to just jump back to that point in the UI, plus when you have multiple levels of pages its to show you where you are.
Here is a link to a typical breadcrumb example which shows what I am talking about.
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_breadcrumbs

The images could still be the hyperlink to keep it looking cool.

**Comment by nickm324** [comment]
If that is not worth messing with I would remove that altogether. When I first saw it I though it was an error in the code, mainly because it seems like it was like an unclosed html tag and the text was bleeding onto the page.

**Comment by tyger07** [comment]
I know how breadcrumbs are supposed to work, but I don't see its value here.  Like, there is no WHATEVER after PLAYER STATS.  There aren't enough ways to branch in order to need that functionality.

I just called it "breadcrumbs" because it is located where breadcrumbs would be, and I didn't know what else to call it.

It's purpose is to provide a way to get back to the server list index.  If you had multiple servers, you would understand its purpose.  The server list is available at the top of the page (under the banner image), but the index page has extra functionality -- such as seeing which map is playing on each server, the number of players in each server, each server name, etcetera, for all of the servers at the same time.

**Comment by nickm324** [comment]
I get it, I would probably replace (if I was designing it) with maybe a dropdown list or any other intuitive way to allow people to use that to navigate between servers if there are more than one. Or maybe enhance that Index and text a little so it dont look like it's not supposed to be there.

**Comment by nickm324** [comment]
If more than one server , maybe have a grid at the top that shows all the servers, and when you click on one the content below changes to that servers content.

I only have one server so I am assuming there is another part of the interface I am not seeing that probably puts it all into a better perspective. Do you know of a site that has more than one server running so I can take a look and maybe offer better feedback.

**Comment by tyger07** [comment]
> I get it, I would probably replace (if I was designing it) with maybe a dropdown list or any other intuitive way to allow people to use that to navigate between servers if there are more than one. Or maybe enhance that Index and text a little so it dont look like it's not supposed to be there.

There is a dropdown list.  It is at the top of the page (below the server banner).  But like I said, the dropdown list doesn't provide as much information as the server index page.

This is the first example I found of a stats page with multiple servers:
https://stats.freiezocker.de/

**Comment by tyger07** [comment]
Here is an example of a server stats index page:
https://banzore.com/bf4-stats/

**Comment by nickm324** [comment]
Ok I see how it works now, actually I think its fine in the context of having multiple servers configured, but I would probably make the text larger or something, maybe use some images in place of the text, The text is so small compared to any other part of the UI, which still gives me the feeling it shouldn't be there. 
![image](https://user-images.githubusercontent.com/6774571/111544856-221fcc80-8743-11eb-88b0-7126c93e5600.png)


I would definitely make it more prominent since it is actually an important navigation function now that I see what its suppose to do. And I would probably completely hide it if only one server is active.

**Comment by nickm324** [comment]
I would at least change the text "index" to something like Server List Index or something like that and make it larger for anything that will be displayed in that div or whatever its container is.

**Comment by tyger07** [comment]
Yeah, I agree that it is kind of small and placed weirdly.  The problem is that some server names are ridiculously long, and it can look kind of weird, when the text is bigger, when the server name is ridiculously long.

Maybe it could be bigger text with the end of name chopped off, if the server name is too long.

Or, maybe it could be in a darker box like almost every other text on the page.

And maybe it could just be hidden if there aren't multiple servers.

**Comment by nickm324** [comment]
Also I think there is a broken image src, This happens on mine the the one you set me to with multiple servers.
![image](https://user-images.githubusercontent.com/6774571/111545509-2a2c3c00-8744-11eb-8700-181940135bda.png)

**Comment by nickm324** [comment]
> Yeah, I agree that it is kind of small and placed weirdly. The problem is that some server names are ridiculously long, and it can look kind of weird, when the text is bigger, when the server name is ridiculously long.
> 
> Maybe it could be bigger text with the end of name chopped off, if the server name is too long.
> 
> Or, maybe it could be in a darker box like almost every other text on the page.
> 
> And maybe it could just be hidden if there aren't multiple servers.

I like the hiding if not multiple servers, and maybe put it in the darker box and a little larger text.
I dont have any multiple servers to test with but what about adding a new config option that they can define a short name for their server and you use that in that display text to handle dealing with really long names.

**Comment by tyger07** [comment]
> Also I think there is a broken image src, This happens on mine and the one you set me to with multiple servers.
> ![image](https://user-images.githubusercontent.com/6774571/111545509-2a2c3c00-8744-11eb-8700-181940135bda.png)

Yes, I am aware. https://github.com/tyger07/BF4-Server-Stats/issues/31

**Comment by tyger07** [comment]
> Also I think there is a broken image src, This happens on mine and the one you set me to with multiple servers.
> ![image](https://user-images.githubusercontent.com/6774571/111545509-2a2c3c00-8744-11eb-8700-181940135bda.png)

How about after the latest update?  Good?  Bad?

**Comment by nickm324** [comment]
I didnt get a notification there was an update. I will download and install it tonight and let you know.

**Comment by nickm324** [comment]
I couldn't wait to update my site :) 
The updates are great! much cleaner and less distracting and a better server list on the home page.

I found one more broken image link on the servers page, other than that the site looks great.
![image](https://user-images.githubusercontent.com/6774571/112543806-42273f80-8d84-11eb-8d75-307f0f873ba6.png)

**Comment by tyger07** [comment]
It is loading fine for me.  I think maybe you are seeing the cached broken image, instead of the fixed image.  Try CTRL + F5 in your browser to refresh your browser's cache.

**Comment by nickm324** [comment]
yep, looks good now.

**Comment by tyger07** [comment]
> I didnt get a notification there was an update. I will download and install it tonight and let you know.

Yeah, no problem.
Just FYI, the stats page lets you know if an update has been released.  
<img width="485" alt="Capture" src="https://user-images.githubusercontent.com/6035184/112703084-ebd50200-8e52-11eb-8ebb-42432f40eb97.PNG">

**Comment by tyger07** [comment]
Hi,
I am sorry to be a bother, but since I don't have a live database to test with any more, it would sure be nice if you could update your server stats page to the current version so that I can see whether it is working properly.
Thanks!

**Comment by nickm324** [comment]
I did update it 3 days ago. Thought we already discussed the updates you made.

**Comment by tyger07** [comment]
Yes, but there were updates since then.

________________________________

**Comment by nickm324** [comment]
Ok I guessed I missed that.

**Comment by nickm324** [comment]
Ok my site is updated with the lastest.

**Comment by tyger07** [comment]
Thank you so much!

**Comment by nickm324** [comment]
> Thank you so much!

Thank you, not many people are willing to maintain stuff related to BF4 these days since its so old and not the "in game" so to speak.

**Comment by nickm324** [comment]
I updated to the 4-4-21 version on my site.

**Comment by tyger07** [comment]
Cool, cool.
Thanks for the heads up!

It looks like you may have accidentally updated your config file with the default config file, so that it is no longer able to connect to your database.

________________________________

**Comment by nickm324** [comment]
Yea I overwrote it, DOH!

Its working now.

**Comment by nickm324** [comment]
Is there something specific I need to do to get the suspicious players to show up? I know I have had few on my server like for example I had one hacker on there that had 69 kills with a 96% headshot rate but nothing shows up under the Suspicious players page.

**Comment by tyger07** [comment]
No, there is nothing specific that you need to do.

My code will display someone as suspicious if the following conditions are met:

Their KDR is greater than 5, and their HSR is greater than 70%, and they have more than 30 kills, and they have have played more than 1 round in the server.

OR

Their KDR is greater than 10, and they have more than 50 kills, and they have played more than 1 round in the server.


If they get detected and banned from the server quickly, they won't have enough stats to meet that criteria.
