### ISSUE TITLE
My server ran over without being paid the IP Switched and now i have 2 DIff server listed on my stats site

### ISSUE THREAD

**Issue by Anthdawg5443** [tyger07/BF4-Server-Stats#34]
not too sure how to fix it one is 0/64 people the other is the actual serve now but i would like to only have one serve listed with both servers combined into one again

**Comment by tyger07** [comment]
This isn't an "issue".   This isn't something I have control over.
When I have time, I will try to tell you how to fix it, but this isn't an "issue" with my code, and therefore I will apply the label "invalid", "won't fix", and will close this.

**Comment by tyger07** [comment]
Does this make sense using words only?
https://myrcon.net/topic/162-chat-guid-stats-and-mapstats-logger-1003/page/16/?tab=comments#comment-45255

**Comment by tyger07** [comment]
Otherwise, create an account on the [myrcon website](https://myrcon.net/) and PM me the details necessary to log into your stats database with edit permission, and I will do it for you.

**Comment by Anthdawg5443** [comment]
so i have got it switched, now i wonder if there is a way to transfer the 6k people that have been listed on the "active" server ID 2?

**Comment by tyger07** [comment]
Nope.  I mean, anything can be done if you try hard enough, but it is prohibitively difficult.  XpKiller, the person who created the statslogger plugin, couldn't even wrap his head around how to do it safely and effectively.

**Comment by Anthdawg5443** [comment]
Ah, itll be alright just glad thats fixed man i appreciate your time completly forgot about the rcon website so sorry to throw an "issue" out here man
