### ISSUE TITLE
Showing deleted server as if it is still there and online with conecred clients

### ISSUE THREAD

**Issue by Ryckie** [tyger07/BF4-Server-Stats#36]
### Expected Behavior:
I was expecting I could set the server ID to 1 and it would continue using the stats from that server using the stats plugin.
Instead it created a new server ID wish I can not change.
I expected this to sync over or at the very least not show a server that is offline.

### Actual Behavior:
Now it is showing an extra server and the original one is also still showing as if it is still online, player count and everything is still showing.

https://vps.deadfriendsgaming.com/bf4stats/

### Steps Performed to Reproduce this Behavior:
delete one of your servers hosted and add it again with a new server port.

**Comment by tyger07** [comment]
This is not an issue with my stats webpage.  I suggest that you seek help regarding using the procon stats plugin (which is what controls what data is stored in the stats database).
https://myrcon.net/topic/162-chat-guid-stats-and-mapstats-logger-1003/
