### ISSUE TITLE
no MAP STATS

### ISSUE THREAD

**Issue by Jhinta** [tyger07/BF4-Server-Stats#38]
MAP STATS does show the maps but not the uper parts any id?
Also county not working.
https://jhinta.com/BF4-Server-Stats/index.php?p=maps&sid=1

**Comment by tyger07** [comment]
No, I have no idea.
Do you have access to phpmyadmin to run a sql query and view the result?
If so, please execute this query and let me know what the result is:

SELECT `MapName`, SUM(`NumberofRounds`) AS number, sub.`total`
FROM `tbl_mapstats`
LEFT JOIN
	(
		SELECT SUM(`NumberofRounds`) AS total
		FROM `tbl_mapstats`
		WHERE `ServerID` = 1
                AND `Gamemode` != ''
		LIMIT 0, 1
	) sub ON sub.`total` = `total`
WHERE `ServerID` = 1
AND `Gamemode` != ''
GROUP BY `MapName`
ORDER BY number DESC
LIMIT 25

**Comment by tyger07** [comment]
Also, I noticed that you have other stuff missing or disabled.  Please ensure that you are using the following settings in XpKiller's Procon stats logging plugin:

"Enable Statslogging?" : Yes
"Enable Weaponstats?" : Yes
"Enable Livescoreboard in DB?" : Yes
"tableSuffix" : None
"MapStats ON?" : Yes
"Session ON?" : Yes
"Save Sessiondata to DB?" : Yes
"Log playerdata only (no playerstats)?" : No

**Comment by tyger07** [comment]
To illustrate, I see all of these oddities, which makes me think that you have a plugin, configuration, or database issue at play.
<img width="705" alt="missing" src="https://user-images.githubusercontent.com/6035184/123172473-0e66bf00-d432-11eb-9c5b-7e9b6511768d.png">

**Comment by Jhinta** [comment]
> No, I have no idea.
> Do you have access to phpmyadmin to run a sql query and view the result?
> If so, please execute this query and let me know what the result is:
> 
> > SELECT `MapName`, SUM(`NumberofRounds`) AS number, sub.`total`
> > FROM `tbl_mapstats`
> > LEFT JOIN
> > (
> > SELECT SUM(`NumberofRounds`) AS total
> > FROM `tbl_mapstats`
> > WHERE `ServerID` = 1
> > AND `Gamemode` != ''
> > LIMIT 0, 1
> > ) sub ON sub.`total` = `total`
> > WHERE `ServerID` = 1
> > AND `Gamemode` != ''
> > GROUP BY `MapName`
> > ORDER BY number DESC
> > LIMIT 25

i get this 
#1055 - Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sub.total' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by tyger07** [comment]
Ah, I see.
There appear to be two options.
1) You could disable ONLY_FULL_GROUP_BY for your SQL database.
2) I could learn to SQL query better.
The second one, I am not sure about.  We'll see.

I would recommend that you disable "ONLY_FULL_GROUP_BY" for your SQL database, and then things should work properly.

**Comment by Jhinta** [comment]
ahh is a google sql problem , is has no super user. so fixed by removing ONLY_FULL_GROUP_BY

**Comment by Jhinta** [comment]
> To illustrate, I see all of these oddities, which makes me think that you have a plugin, configuration, or database issue at play.
> <img alt="missing" width="705" src="https://user-images.githubusercontent.com/6035184/123172473-0e66bf00-d432-11eb-9c5b-7e9b6511768d.png">

btw the player count sould be correct , my gues its not showing spectators?
