### ISSUE TITLE
Problems with the unfair BAN

### ISSUE THREAD

**Issue by Bred1982** [tyger07/BF4-Server-Stats#39]
Good afternoon!
Some time ago, when connecting to your favorite server, "! [EGL] HARDCORE TDM CLASSICS ALL WEAPONS" received a message: Game is disabled: you have been excluded by the administrator. Reason specified: [BF4DB] Multihack. Appeal at https://bf4db.com/player/ban/10046681 [perm] [BF4DB].

I've never used cheats. I turned to the bf4DB.com administration and received a confirmation that I did not have a ban. I am attaching a screenshot of the correspondence with advice to contact the Administrator of your site. My son MBL2010 has a similar problem.

I am attaching a screen with my statistics and with the statistics of my son on bf4DB.com.

Please help resolve the issue and let me and my son to continue playing on your server.

![Stats MBL2010](https://user-images.githubusercontent.com/88590695/128626804-6879df6a-d4b7-4199-a85e-192f86d7c699.png)
![Dialog with the BF4DB](https://user-images.githubusercontent.com/88590695/128626805-445e51de-ff2c-4f22-b866-a59eea46ea98.png)
![Stats Bred1982](https://user-images.githubusercontent.com/88590695/128626806-1d07e8a1-95a6-4bc8-9123-4b7be98b7997.png)

**Comment by tyger07** [comment]
Hi,
I have know idea who EGL is and have nothing to do with EGL.  Their clan is simply using the webpage code that I have provided for people to use.
If you want to appeal your BF4DB ban, I am pretty sure that you need to contact someone at BF4DB.
