### ISSUE TITLE
Loading issues on Maps and Server Info pages

### ISSUE THREAD

**Issue by nickm324** [tyger07/BF4-Server-Stats#41]
### Expected Behavior:
Server info and Maps to load

### Actual Behavior:
Server and Maps pages just show spinning loading indicator and never loads the pages.

### Steps Performed to Reproduce this Behavior:
pull up the site and click the MAPS or SERVICE INFO tabs.
https://i.imgur.com/53C7707.png

**Comment by tyger07** [comment]
I haven't seen that before. Can you provide a link?

**Comment by nickm324** [comment]
lsd.thinkdevtech.com

**Comment by nickm324** [comment]
Also you will notice several of the pages with mysql errors likely because there are no records in the table, but still should not display the error message in the UI.

Warning: Trying to access array offset on value of type null in /var/www/html/common/home/home.php on line 71

**Comment by tyger07** [comment]
Have you tried using the test database included to verify that you can reproduce the issue?  Otherwise, it could be a database or xpkiller plugin setup issue.
I see what you mean about the empty array problem, and obviously I could put some checks in to handle it better, but it isn't normal for an active server to return that empty result.
With your wiped database, it isn't really possible for me to guess how it would act with a properly-functioning database.  Again, I would suggest that you try again with the included test database.

**Comment by tyger07** [comment]
Ah, I see that every file in those affected folders are returning a 500 internal server error reponses.  It seems your webserver doesn't like the .htaccess rewrite rules in those folders.

**Comment by tyger07** [comment]
I updated home.php so that it should not try to count the number of rows in an empty array.  That will solve the "Also you will notice several of the pages with mysql errors likely because there are no records in the table, but still should not display the error message in the UI." thing.  Please verify.

**Comment by tyger07** [comment]
Regarding Maps and Server Stats loading problems, please see what you can do to figure out why your webserver is unhappy with the .htaccess files at the following locations:

https://lsd.thinkdevtech.com/common/maps/.htaccess
https://lsd.thinkdevtech.com/common/maps/images/.htaccess
https://lsd.thinkdevtech.com/common/server/.htaccess
https://lsd.thinkdevtech.com/common/server/images/.htaccess


Those .htaccess files are designed to make some .php files accessible as a .png extension.

**Comment by nickm324** [comment]
should those be viewable from the internet?

**Comment by tyger07** [comment]
Viewable? No.  But they should function.  At the moment they aren't functioning, and I don't know why.  I imagine that there is an error log on your web server that says why.  I imagine it is a web server security setting that is blocking their operation.

**Comment by nickm324** [comment]
ok I will try and look at the logs, but strangely most of the other pages work.

**Comment by nickm324** [comment]
see this in the log when I try and access the server info page.

192.168.0.82 - - [01/Oct/2022:18:14:41 +0000] "GET /common/server/serverstats.php?gid=1&sid=1&p=server HTTP/1.1" 500 810 "https://lsd.thinkdevtech.com/index.php?p=server&sid=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"

**Comment by nickm324** [comment]
Another mysql error on the player stats page which does have data
![image](https://user-images.githubusercontent.com/6774571/193423532-0bf7917f-2e8c-4b8c-a504-a5cb950ebd71.png)

Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in /var/www/html/common/functions.php:370 Stack trace: #0 /var/www/html/common/functions.php(370): mysqli_num_rows(false) #1 /var/www/html/common/player/player-ranks.php(49): rank('1', '1', '1', Object(mysqli), '1', NULL) #2 {main} thrown in /var/www/html/common/functions.php on line 370

**Comment by tyger07** [comment]
> Another mysql error on the player stats page which does have data ![image](https://user-images.githubusercontent.com/6774571/193423532-0bf7917f-2e8c-4b8c-a504-a5cb950ebd71.png)
> 
> Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in /var/www/html/common/functions.php:370 Stack trace: #0 /var/www/html/common/functions.php(370): mysqli_num_rows(false) #1 /var/www/html/common/player/player-ranks.php(49): rank('1', '1', '1', Object(mysqli), '1', NULL) #2 {main} thrown in /var/www/html/common/functions.php on line 370


That is unrelated

**Comment by nickm324** [comment]
Here the permission on the one of the .htaccess files.
![image](https://user-images.githubusercontent.com/6774571/193423618-2d114399-b66b-4d5d-972a-954957891cc4.png)

**Comment by tyger07** [comment]
> ok I will try and look at the logs, but strangely most of the other pages work.

If you try to visit those .htaccess files I linked above, the result should be a blank page, or a 403 forbidden page.

It should not be a 500 error.

**Comment by nickm324** [comment]
Here is the actual error message. I have mod_rewrite enabled so I dont know why it would not know it is valid.


[Sat Oct 01 22:57:58.031213 2022] [core:alert] [pid 19] [client 192.168.0.82:43442] **/var/www/html/common/server/.htaccess:** **Invalid command 'RewriteEngine'**, perhaps misspelled or defined by a module not included in the server configuration, referer: https://lsd.thinkdevtech.com/index.php?p=server&sid=1

**Comment by tyger07** [comment]
I don't know. Sounds like a question for your server host.

**Comment by tyger07** [comment]
> Another mysql error on the player stats page which does have data ![image](https://user-images.githubusercontent.com/6774571/193423532-0bf7917f-2e8c-4b8c-a504-a5cb950ebd71.png)
> 
> Fatal error: Uncaught TypeError: mysqli_num_rows(): Argument #1 ($result) must be of type mysqli_result, bool given in /var/www/html/common/functions.php:370 Stack trace: #0 /var/www/html/common/functions.php(370): mysqli_num_rows(false) #1 /var/www/html/common/player/player-ranks.php(49): rank('1', '1', '1', Object(mysqli), '1', NULL) #2 {main} thrown in /var/www/html/common/functions.php on line 370

That error should go away once you have at least 20 players in your database, I think.

This should probably be assigned a new issue # for me to work on when I have time.

**Comment by nickm324** [comment]
I am hosting this myself. I have full access, I have verified mod rewrite is installed and loaded yet it doesn't seem to matter.

**Comment by nickm324** [comment]
Finally got it all working. Had to reconfigure my docker image and add a few things like gd and ziplib and libpng.

**Comment by tyger07** [comment]
great!
