### ISSUE TITLE
Deprecated on Php8 - Actually Fixed in this post as well

### ISSUE THREAD

**Issue by TresIqus94** [tyger07/BF4-Server-Stats#43]
Deprecated: Implicit conversion from float 3.6 to int loses precision in path/to/player.php on line 441
^^ change 	$Playminutes = floor(($Playtime / 60) % 60); to $Playminutes = floor($Playtime / 60);

Deprecated: round(): Passing null to parameter #1 ($num) of type int|float is deprecated in path/to/player.php on line 451
^^ change 	$KDR = round($PlayerData_r['KDR'],2); to $KDR = round(($PlayerData_r['KDR']*1),2);

Deprecated: round(): Passing null to parameter #1 ($num) of type int|float is deprecated in path/to/player.php on line 455
^^ change 	$WLR = round($PlayerData_r['WLR'],2) * 100; to $WLR = round(($PlayerData_r['WLR']*100),2);

Deprecated: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in path/to/functions.php on line 2589
^^ change $content = str_replace(array('\'', '"', '\\', '`'), '',htmlspecialchars(strip_tags($content)));
to
$content = str_replace(array('\'', '"', '\\', '`'), '',htmlspecialchars(strip_tags((string) $content)));

Fatal error: Uncaught mysqli_sql_exception: Unknown column 'tps.Score' in 'order clause' in path/to/html-banner-content.php:339 Stack trace: #0 path/to/html-banner-content.php(339): mysqli_query() #1 {main} thrown in path/to/html-banner-content.php on line 339
^^ This one says line 339 but when I change 	ORDER BY tps.`Score` DESC, tpd.`SoldierName` ASC LIMIT 10 to 
ORDER BY `Score` DESC, `SoldierName` ASC LIMIT 10 it no longer gives the Fatal error

This is for Php8 and above

**Comment by tyger07** [comment]
Thanks for the report!

I'll plan to update the code when I have the time.

**Comment by tyger07** [comment]
That one in html-banner-content.php was dumb of me.  I should have caught that much earlier.

Thank you!  I have fixed this!

**Comment by TresIqus94** [comment]
Your Welcome sorry it took me awhile to respond I have been busy with my job

Closing the Issue
